{"issue":{"title":"[CF 257] Error upon logging - TMW unusable. ","body":" <p>Here is the error:</p><p>Date: 2011-07-15 17:55:34<br>ID: 3<br>Error occured in: Global<br>Count: âˆž<br>Message: ..\\AddOns\\TellMeWhen\\conditions.lua line 319:<br>&nbsp;&nbsp; attempt to perform arithmetic on local 'start' (a nil value)<br>Debug:<br>&nbsp;&nbsp; [C]: ?<br>&nbsp;&nbsp; TellMeWhen\\conditions.lua:319: CooldownDuration()<br>&nbsp;&nbsp; [string \"TellMeWhen_Group2_Icon1 Condition\"]:1: CndtCheck()<br>&nbsp;&nbsp; TellMeWhen\\Types\\cooldown.lua:137: OnUpdate()<br>&nbsp;&nbsp; TellMeWhen\\TellMeWhen.lua:1137:<br>&nbsp; &nbsp; &nbsp; TellMeWhen\\TellMeWhen.lua:1105</p><p>1. I made a simple interrupt icon based on Pummel spell and two conditions: spell is usable and target is casting an interruptable spell.</p><p>2. After locking the addon I got this error and now I encounter it whenever I log in. Also can't edit it back. /tmw command does not work.</p><p>3. Using version 4.4.4</p><p>4. SV.lua attached, maybe you figure what is going wrong.</p> \n<br>\n\n> Posted by CurseForge user <a href=\"https://wow.curseforge.com/members/oushies\">oushies</a> | Imported from CurseForge issue <a href=\"https://wow.curseforge.com/projects/tellmewhen/issues/257\">#257</a> | <a href=\"https://github.com/tmw-issue-import/dump/blob/master/html/257.html\">Raw</a>","closed":true,"closed_at":"2011-07-16T00:28:52Z","created_at":"2011-07-15T16:09:42Z","updated_at":"2016-11-01T00:55:26Z","labels":["defect","resolved"]},"comments":[]}