{"issue":{"title":"[CF 598] Lua Error in r586 ","body":" <p>FYI -- I'm getting the following error on start up - running r586 (doesn't seem to be affecting functionality in anyway):</p><p>Date: 2012-09-08 07:56:31<br>ID: 1<br>Error occured in: Global<br>Count: 1<br>Message: [string \"table: 000000002C1C0530 Condition\"] line 2:<br>&nbsp;&nbsp; attempt to compare number with nil<br>Debug:<br>&nbsp;&nbsp; (tail call): ?<br>&nbsp;&nbsp; [string \"table: 000000002C1C0530 Condition\"]:2: CheckFunction()<br>&nbsp;&nbsp; ...TellMeWhen\\Components\\Core\\Conditions\\Conditions.lua:1011: Check()<br>&nbsp;&nbsp; ...TellMeWhen\\Components\\Core\\Conditions\\Conditions.lua:844:<br>&nbsp; &nbsp; &nbsp; ...TellMeWhen\\Components\\Core\\Conditions\\Conditions.lua:823<br>&nbsp;&nbsp; (tail call): ?<br>&nbsp;&nbsp; [C]: ?<br>&nbsp;&nbsp; [string \"safecall Dispatcher[3]\"]:9:<br>&nbsp; &nbsp; &nbsp; [string \"safecall Dispatcher[3]\"]:5<br>&nbsp;&nbsp; (tail call): ?<br>&nbsp;&nbsp; TellMeWhen\\TellMeWhen.lua:849:<br>&nbsp; &nbsp; &nbsp; TellMeWhen\\TellMeWhen.lua:820<br>&nbsp;&nbsp; TellMeWhen\\TellMeWhen.lua:998:<br>&nbsp; &nbsp; &nbsp; TellMeWhen\\TellMeWhen.lua:973<br>&nbsp;&nbsp; (tail call): ?<br>&nbsp;&nbsp; ...TellMeWhen\\Components\\Core\\Conditions\\Conditions.lua:1196: Construct()<br>&nbsp;&nbsp; TellMeWhen\\TellMeWhen.lua:3872:<br>&nbsp; &nbsp; &nbsp; TellMeWhen\\TellMeWhen.lua:3827<br>&nbsp;&nbsp; (tail call): ?<br>&nbsp;&nbsp; [C]: ?<br>&nbsp;&nbsp; [string \"safecall Dispatcher[1]\"]:9:<br>&nbsp; &nbsp; &nbsp; [string \"safecall Dispatcher[1]\"]:5<br>&nbsp;&nbsp; (tail call): ?<br>&nbsp;&nbsp; TellMeWhen\\TellMeWhen.lua:3448:<br>&nbsp; &nbsp; &nbsp; TellMeWhen\\TellMeWhen.lua:3403<br>&nbsp;&nbsp; (tail call): ?<br>&nbsp;&nbsp; [C]: ?<br>&nbsp;&nbsp; [string \"safecall Dispatcher[1]\"]:9:<br>&nbsp; &nbsp; &nbsp; [string \"safecall Dispatcher[1]\"]:5<br>&nbsp;&nbsp; (tail call): ?<br>&nbsp;&nbsp; TellMeWhen\\TellMeWhen.lua:1919: Update()<br>&nbsp;&nbsp; TellMeWhen\\TellMeWhen.lua:2773: ?()<br>&nbsp;&nbsp; ...Ons\\Ace3\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:147:<br>&nbsp; &nbsp; &nbsp; ...Ons\\Ace3\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:147<br>&nbsp;&nbsp; [string \"safecall Dispatcher[1]\"]:4:<br>&nbsp; &nbsp; &nbsp; [string \"safecall Dispatcher[1]\"]:4<br>&nbsp;&nbsp; [C]: ?<br>&nbsp;&nbsp; [string \"safecall Dispatcher[1]\"]:13: ?()<br>&nbsp;&nbsp; ...Ons\\Ace3\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:92: Fire()<br>&nbsp;&nbsp; Ace3\\AceEvent-3.0\\AceEvent-3.0.lua:120:<br>&nbsp; &nbsp; &nbsp; Ace3\\AceEvent-3.0\\AceEvent-3.0.lua:119<br>Locals:<br>None</p> \n<br>\n\n> Posted by CurseForge user <a href=\"https://wow.curseforge.com/members/WarHopper\">WarHopper</a> | Imported from CurseForge issue <a href=\"https://wow.curseforge.com/projects/tellmewhen/issues/598\">#598</a> | <a href=\"https://github.com/tmw-issue-import/dump/blob/master/html/598.html\">Raw</a>","closed":true,"closed_at":"2012-09-08T07:04:56Z","created_at":"2012-09-08T07:00:10Z","updated_at":"2012-09-08T07:04:56Z","labels":["defect","invalid"]},"comments":[{"body":" <p>Please do not ignore the default ticket template and the instructions it gives.</p>\r\n<p>You need to post the export string of the profile that you are getting this error with for me to be able to debug it.</p> <div class=\"project-issue-comment-body-modified\"> </div> \n<br>\n\n> Posted by CurseForge user <a href=\"https://wow.curseforge.com/members/Cybeloras\">Cybeloras</a>","created_at":"2012-09-08T07:04:12Z"}]}